"""
SQLAlchemy ORM models — all tables prefixed with 'crypto_'.
Uses the existing PostgreSQL instance alongside the AI Data Copilot tables.
"""
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    BigInteger, Boolean, DateTime, ForeignKey,
    Integer, Numeric, String, Text, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class Signal(Base):
    """Every BUY/SELL/HOLD signal generated by the strategy."""
    __tablename__ = "crypto_signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    timeframe: Mapped[str] = mapped_column(String(10), nullable=False)
    signal_type: Mapped[str] = mapped_column(String(10), nullable=False)   # BUY | SELL | HOLD

    # Price levels
    entry_price: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    stop_loss: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    target: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    position_size_inr: Mapped[Optional[float]] = mapped_column(Numeric(20, 2))

    # Indicator snapshot
    close_price: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    ema200: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    rsi: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    macd: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    macd_signal: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    macd_hist: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    volume_ratio: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))

    # AI filter result
    ai_confidence: Mapped[Optional[int]] = mapped_column(Integer)
    ai_reasoning: Mapped[Optional[str]] = mapped_column(Text)
    ai_decision: Mapped[Optional[str]] = mapped_column(String(10))

    # Alert tracking
    alert_sent: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )

    trade: Mapped[Optional["Trade"]] = relationship("Trade", back_populates="signal", uselist=False)

    def __repr__(self) -> str:
        return f"<Signal {self.symbol} {self.signal_type} @ {self.entry_price}>"


class Trade(Base):
    """Manual or tracked trade linked to a signal."""
    __tablename__ = "crypto_trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    signal_id: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("crypto_signals.id"), index=True
    )
    symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    signal_type: Mapped[str] = mapped_column(String(10), nullable=False)

    entry_price: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    exit_price: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    stop_loss: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    target: Mapped[Optional[float]] = mapped_column(Numeric(20, 8))
    position_size_inr: Mapped[Optional[float]] = mapped_column(Numeric(20, 2))

    pnl_inr: Mapped[Optional[float]] = mapped_column(Numeric(20, 2))
    pnl_pct: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))

    # OPEN | CLOSED_WIN | CLOSED_LOSS | STOPPED | CANCELLED
    status: Mapped[str] = mapped_column(String(20), default="OPEN")
    notes: Mapped[Optional[str]] = mapped_column(Text)

    opened_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    closed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    signal: Mapped[Optional["Signal"]] = relationship("Signal", back_populates="trade")

    def __repr__(self) -> str:
        return f"<Trade {self.symbol} {self.status} PnL={self.pnl_inr}>"


class BacktestResult(Base):
    """Stored result of a backtest run."""
    __tablename__ = "crypto_backtest_results"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(10), nullable=False)
    start_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    end_date: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    total_trades: Mapped[int] = mapped_column(Integer, default=0)
    winning_trades: Mapped[int] = mapped_column(Integer, default=0)
    losing_trades: Mapped[int] = mapped_column(Integer, default=0)
    win_rate: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    total_return_pct: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    max_drawdown_pct: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    sharpe_ratio: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    avg_win_pct: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    avg_loss_pct: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    def __repr__(self) -> str:
        return f"<Backtest {self.symbol} win_rate={self.win_rate}%>"


class BotRun(Base):
    """Log of every scheduler execution."""
    __tablename__ = "crypto_bot_runs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    symbols_checked: Mapped[Optional[str]] = mapped_column(String(200))
    signals_generated: Mapped[int] = mapped_column(Integer, default=0)
    alerts_sent: Mapped[int] = mapped_column(Integer, default=0)
    duration_ms: Mapped[Optional[int]] = mapped_column(Integer)
    status: Mapped[str] = mapped_column(String(20), default="SUCCESS")
    error: Mapped[Optional[str]] = mapped_column(Text)

    def __repr__(self) -> str:
        return f"<BotRun {self.run_at} {self.status} signals={self.signals_generated}>"
